version: '3.7'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  # Production mode, uses Cognito for auth
  feature-creep-server:
    image: squadserver:v2
    depends_on: 
      - redis
    ports:
      - 4000:4000
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=production
  feature-creep-client:
    image: squadclient:v2
    depends_on: 
      - feature-creep-server
    ports:
      - 3000:3000
volumes:
  redis:
